package com.example.snakedroid.game.cell;

public enum CellType {
    WALL_TOP,
    WALL_BOTTOM,
    WALL_LEFT,
    WALL_RIGHT,
    CORNER_TOP_LEFT,
    CORNER_TOP_RIGHT,
    CORNER_BOTTOM_LEFT,
    CORNER_BOTTOM_RIGHT,
    OBSTACLE_1,
    OBSTACLE_2,
    SNAKE_HEAD,
    SNAKE_BODY,
    SNAKE_BODY_CORNER_TOP_LEFT,
    SNAKE_BODY_CORNER_TOP_RIGHT,
    SNAKE_BODY_CORNER_BOTTOM_LEFT,
    SNAKE_BODY_CORNER_BOTTOM_RIGHT,
    SNAKE_TAIL,
    OBJECT_APPLE,
    OBJECT_GRAPE,
    OBJECT_BANANA,
    EMPTY
}
